### ISSUE TITLE
Cannot upgrade @middy/core to v5.x

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#3681]
Upgrading @middy/core failes the unit test. Issue looks related to https://github.com/middyjs/middy/issues/1148

See also: #3724

**Comment by npalm** [comment]
https://middy.js.org/docs/intro/testing/

**Comment by saragerion** [comment]
Hello @npalm!

**Concerning the usage of Powertools for AWS Lambda (TypeScript) and Middy v5**: the current Powertools version 1.18.0 officially supports Middy up until version 3, as described in the [documentation](https://docs.powertools.aws.dev/lambda/typescript/1.18.0/core/logger/#capturing-lambda-context-info).

Official support for Middy v4 is expected to be launched soon as part of [the upcoming major release 2.x](https://github.com/aws-powertools/powertools-lambda-typescript/issues/1694#issuecomment-1790427042).

I opened a [feature request](https://github.com/aws-powertools/powertools-lambda-typescript/issues/2049) for official support of Middy v5. 


**Concerning the usage of Middy v5 and Jest**: it seems like the libraries can be used together successfully by using these [tsconfig setup](https://github.com/middyjs/middy/issues/1148#issuecomment-1862559958).

Can you share the errors that you are getting in the unit tests?

**Comment by vks-dbb** [comment]
Hi @saragerion, still getting the same error on @middy/core: 5.2.4, 

Cannot find module '@middy/core' or its corresponding type declarations.
import middy from '@middy/core'

my jest.config.ts

{
  preset: 'ts-jest',
  extensionsToTreatAsEsm: ['.ts'],
  testMatch: ['**/(__tests__|src)/**/*.(test|spec|e2e-spec).(ts)'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  transform: {
    '^.+\\.[tj]sx?$': [
      'ts-jest',
      {
        tsconfig: './tsconfig.spec.json',
        useESM: true
      }
    ]
  },
  testEnvironment: 'node',
  setupFiles: ['dotenv/config'],
  coverageDirectory: './coverage',
  collectCoverage: true,
  coveragePathIgnorePatterns: ['/node_modules/', '/.node/', '/jest/'],
  transformIgnorePatterns: ['/node_modules/(?!(@middy/core)/)'],
  moduleNameMapper: {
    '^@middy/core$': '<rootDir>/node_modules/@middy/core',
    '^(\\.{1,2}/.*)\\.js$': '$1'
  }
}

**Comment by saragerion** [comment]
Hi @vks-dbb and @npalm, I tried to reproduce your issue but I cannot. 

Just checking: it seems like the bug is solved? See this comment: https://github.com/philips-labs/terraform-aws-github-runner/pull/3789#issuecomment-1975097042

If the bug was caused by the Powetools library, can you please open an issue in the Powertools repository?
https://github.com/aws-powertools/powertools-lambda-typescript/issues/new?assignees=&labels=type%2Fbug%2Ctriage&projects=aws-powertools%2F7&template=bug_report.yml&title=Bug%3A+TITLE
After the issue is open, I am happy to have us look into it.

**Comment by npalm** [comment]
No still having the issue when updating middy. But looks like not a powertools issue.

**Comment by saragerion** [comment]
Thanks for clarifying @npalm!
